# Generated by Django 3.2 on 2023-01-19 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemprice',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_price', to='item.item'),
        ),
    ]
